# Generated by Django 4.0 on 2021-12-20 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('melophony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('INITIAL', 'INITIAL'), ('UNAVAILABLE', 'UNAVAILABLE'), ('AVAILABLE', 'AVAILABLE'), ('ERROR', 'ERROR'), ('DOWNLOADING', 'DOWNLOADING')], default='INITIAL', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('last_play', models.DateTimeField(auto_now=True)),
                ('play_count', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('progress', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='melophony.album')),
                ('artist', models.ManyToManyField(to='melophony.Artist')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melophony.file')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracks', models.ManyToManyField(to='melophony.Track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melophony.user')),
            ],
        ),
    ]
