# Generated by Django 4.0 on 2021-12-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melophony', '0003_alter_album_name_alter_artist_name_alter_track_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
