# Generated by Django 4.0 on 2021-12-22 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('melophony', '0005_file_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_name',
            new_name='videoId',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='creation_date',
            new_name='creationDate',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='last_play',
            new_name='lastPlay',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='play_count',
            new_name='playCount',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='start_time',
            new_name='startTime',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
