# Generated by Django 4.0 on 2022-01-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melophony', '0009_playlisttrack_alter_playlist_tracks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
