# Generated by Django 4.0 on 2022-01-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melophony', '0010_artist_image_name_artist_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='image_name',
            new_name='imageName',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='image_url',
            new_name='imageUrl',
        ),
    ]
