# Generated by Django 4.2.2 on 2023-07-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melophony', '0015_rename_videoid_file_fileid'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='lastModification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='lastModification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='track',
            name='lastModification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
