# Generated by Django 4.0 on 2021-12-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melophony', '0006_rename_file_name_file_videoid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='artist',
            new_name='artists',
        ),
    ]
